#!/bin/dash
# FIXME: the top output sometimes isn't PID-ordered. Which breaks everything.
trap "trap - TERM && kill -- -$$" INT TERM EXIT

top \
  -b \
  -d 30 \
| sed \
    --unbuffered \
    's/^ *//;s/ +/ /g' \
| grep \
    --line-buffered \
    '^[0-9]' \
| awk \
    -W interactive \
    'BEGIN {cpupc=0}
     $1=="1" {print "{\"cpu-percent\": " cpupc "}";cpupc=0}
     {cpupc+=$9}'
